document.addEventListener('DOMContentLoaded', () => {
    const citySelect = document.getElementById('city-select');
    const cityNameDisplay = document.getElementById('city-name');
    const cityDescriptionDisplay = document.getElementById('city-description');

    // Objeto com as histórias das cidades
    const cityData = {
        "Cantagalo": `Cantagalo, no Paraná, tem suas raízes na colonização de terras férteis do sudoeste paranaense. A região, inicialmente habitada por povos indígenas, começou a ser explorada por tropeiros e madeireiros no século XIX. O nome "Cantagalo" provavelmente se originou da abundância de galos selvagens na área. A fundação oficial do município ocorreu em 14 de dezembro de 1951, desmembrando-se de Laranjeiras do Sul. Sua economia inicial era baseada na exploração da madeira e, posteriormente, na agricultura, com destaque para a soja e o milho. O desenvolvimento de Cantagalo foi impulsionado pela construção de estradas e pela chegada de imigrantes, principalmente de origem europeia, que contribuíram para a diversidade cultural e econômica da cidade.`,
        "Diamante do Sul": `Diamante do Sul, também localizado no Paraná, é um município jovem com uma história ligada à expansão agrícola da região. Sua emancipação política ocorreu em 1º de janeiro de 1997, desmembrando-se de Nova Laranjeiras. Antes disso, a área era composta por fazendas e pequenos povoados. O nome "Diamante" pode ter sido escolhido pela valorização das terras férteis e do potencial de desenvolvimento local. A economia da cidade é predominantemente agrícola, com lavouras de soja, milho e trigo, além da pecuária. O desenvolvimento de Diamante do Sul reflete o esforço da comunidade em construir uma infraestrutura para atender às necessidades de seus habitantes, mantendo um forte vínculo com o setor primário.`,
        "Espigão Alto do Iguaçu": `Espigão Alto do Iguaçu, no sudoeste do Paraná, é mais um município que se formou a partir do avanço da fronteira agrícola. Sua história está intrinsecamente ligada à colonização e ao uso das terras ao longo do Rio Iguaçu. O município foi emancipado em 1º de janeiro de 1997, desmembrando-se de Nova Laranjeiras e Quedas do Iguaçu. O nome "Espigão Alto" refere-se a uma formação geográfica elevada na região, enquanto "do Iguaçu" indica sua proximidade com o rio homônimo. A economia local é forte na agricultura e na pecuária, com destaque para a produção de grãos. A comunidade tem trabalhado para desenvolver a infraestrutura e os serviços básicos, preservando as características rurais da área.`,
        "Laranjeiras do Sul": `Laranjeiras do Sul é uma das cidades mais antigas e importantes do centro-sul do Paraná, sendo um polo regional. Sua história remonta ao século XIX, com a chegada dos primeiros colonizadores e tropeiros. O nome "Laranjeiras" tem origem na grande quantidade de pés de laranja encontrados na região pelos primeiros desbravadores. A cidade foi oficialmente fundada em 1946. Sua localização estratégica na rota de tropeiros e, posteriormente, com a chegada da Estrada de Ferro, impulsionou seu desenvolvimento. A economia de Laranjeiras do Sul é diversificada, com forte presença da agricultura (soja, milho, trigo), pecuária, indústria madeireira e um crescente setor de serviços e comércio, atendendo a toda a microrregião. A cidade é um centro universitário importante, o que contribui para seu dinamismo.`,
        "Marquinho": `Marquinho, um município relativamente jovem no Paraná, teve sua emancipação em 1º de janeiro de 1997, desmembrando-se de Laranjeiras do Sul. Sua história, assim como a de muitos municípios da região, está ligada à expansão das atividades agrícolas. O nome "Marquinho" é uma homenagem a um dos pioneiros da região ou a uma característica marcante do local. A economia de Marquinho é majoritariamente agrícola, com a produção de grãos e a criação de gado. A comunidade local tem focado no desenvolvimento de infraestrutura básica e na melhoria da qualidade de vida de seus habitantes, mantendo as tradições rurais e o senso de comunidade.`,
        "Nova Laranjeiras": `Nova Laranjeiras, no Paraná, surgiu da necessidade de expandir e organizar o assentamento de terras na região de Laranjeiras do Sul. O município foi emancipado em 1º de janeiro de 1993, desmembrando-se de Laranjeiras do Sul e Rio Bonito do Iguaçu. O nome "Nova Laranjeiras" indica a continuidade e expansão do processo de colonização da área original de Laranjeiras. A economia é fortemente baseada na agricultura, com lavouras de soja, milho e trigo, além da pecuária. O município tem investido no desenvolvimento de sua infraestrutura e na diversificação de sua base econômica, buscando atrair novos investimentos e melhorar a qualidade de vida de seus moradores.`,
        "Porto Barreiro": `Porto Barreiro, localizado no Paraná, tem uma história ligada à navegação fluvial e ao transporte de mercadorias. O município foi emancipado em 1º de janeiro de 1993, desmembrando-se de Laranjeiras do Sul e Foz do Jordão. O nome "Porto Barreiro" sugere a existência de um porto ou ponto de embarque e desembarque em uma área com características de barranco ou barreiro. A economia local é impulsionada pela agricultura e pecuária. A cidade possui um potencial turístico devido à sua proximidade com corpos d'água e belezas naturais. O desenvolvimento de Porto Barreiro tem se concentrado em fortalecer sua economia rural e explorar o potencial turístico e de lazer da região.`,
        "Quedas do Iguaçu": `Quedas do Iguaçu, no sudoeste do Paraná, é um município com uma rica história ligada à exploração madeireira e à formação de grandes projetos agroindustriais. Foi fundado em 1961, desmembrando-se de Laranjeiras do Sul. O nome "Quedas do Iguaçu" faz referência às quedas d'água existentes no Rio Iguaçu, que cortam a região. A cidade se desenvolveu a partir da instalação de grandes empresas madeireiras e, posteriormente, de projetos de assentamento e cooperativas agrícolas. Sua economia é diversificada, com forte presença da agricultura (soja, milho, feijão), pecuária, silvicultura e algumas indústrias. A história de Quedas do Iguaçu é marcada por períodos de grande efervescência econômica e social.`,
        "Rio Bonito": `Rio Bonito, no Paraná, teve sua emancipação em 1º de janeiro de 1990, desmembrando-se de Laranjeiras do Sul. Sua história, como a de muitos municípios vizinhos, está ligada à colonização e ao aproveitamento das terras férteis da região. O nome "Rio Bonito" provavelmente se refere a algum curso d'água de beleza notável na área. A economia do município é predominantemente agrícola, com a produção de grãos, em especial soja e milho, e a criação de gado. A comunidade de Rio Bonito tem trabalhado no desenvolvimento de sua infraestrutura básica e na busca por novas oportunidades de crescimento econômico, mantendo um foco no setor primário.`,
        "Virmond": `Virmond, um município do Paraná, foi emancipado em 1º de janeiro de 1997, desmembrando-se de Laranjeiras do Sul. A história de Virmond, assim como a de muitos municípios da região, está entrelaçada com a expansão da fronteira agrícola. O nome "Virmond" pode ser uma homenagem a alguma família pioneira ou personalidade influente na fundação do povoado. A economia de Virmond é predominantemente agrícola, com o cultivo de grãos e a pecuária como principais atividades. O município tem se esforçado para desenvolver sua infraestrutura e serviços para atender à sua população, ao mesmo tempo em que preserva suas características rurais e o forte senso de comunidade.`,
    };

    citySelect.addEventListener('change', (event) => {
        const selectedCity = event.target.value;

        if (selectedCity) {
            cityNameDisplay.textContent = selectedCity;
            cityDescriptionDisplay.textContent = cityData[selectedCity] || "História não encontrada para esta cidade.";
        } else {
            cityNameDisplay.textContent = "";
            cityDescriptionDisplay.textContent = "Selecione uma cidade para ver sua história.";
        }
    });

    // Mensagem inicial quando a página carrega
    cityNameDisplay.textContent = "";
    cityDescriptionDisplay.textContent = "Selecione uma cidade para ver sua história.";
});